import type { Metadata } from "next";
import "./globals.css";
import TanstackQueryProvider from "@/providers/tanstack-query-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <TanstackQueryProvider>
          <div className="max-w-4xl mx-auto p-4">{children}</div>
        </TanstackQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
